### PR TITLE
Temperatursensor LM35 für Motortemperatur - Anzeige im LCD3

### PR DESCRIPTION
**Pull request by tomsen61**

### CODE REVIEW

**Review by stancecoke — CHANGES_REQUESTED** [review]
Avoid floating points in calibration, better use *16/100, or even better scale it to 41/256 then you can use right shift 8 to avoid the division.

Pin PB1 is Pin1 on GPIOB, so you have to init it accordingly. I wonder that it works the way you've done it ;-)

**Comment by tomsen61** [comment]
ok 41/256>>8 instead 0.16 works fine
but
#define Temperature_Pin GPIO_PIN_9
#define Temperature_GPIO_Port GPIOA
replaced by
#define Temperature_Pin GPIO_PIN_1
#define Temperature_GPIO_Port GPIOB
--> negative: Motor istn't turning, only "tock, tock", but current is flowing.


PS: In _REVERSE_ mode, i_q is negative and by that also _MS.Battery_Current_. The Display need positive sign to display Power. 
Is it ok to use the abs(i) for this?  `MS.Battery_Current =abs(q31_t_Battery_Current_accumulated>>8);

**Review by tomsen61 — COMMENTED** [review]
KT Display only works with positive power values.
Because of negative i_q in REVERSE Mode, MS.Battery_Current would be also negative. So i set at main.c #475 the abs() function to Battery current.

**Comment by stancecoke** [comment]
Thank you! :-)

**Pull request merged**
